# Generated by Django 3.1.4 on 2021-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210205_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('SENDING', 'SENDING'), ('PENDING', 'PENDING')], max_length=12),
        ),
    ]
